copy("teapot") {
  sources = [
    "Cerberus_A.tga",
    "Cerberus_LP.mtl",
    "Cerberus_LP.obj",
    "Cerberus_M.tga",
    "Cerberus_N.tga",
    "Cerberus_R.tga",
    "Cube.bin",
    "Cube.gltf",
    "Cube_BaseColor.png",
    "Cube_MetallicRoughness.png",
    "WaterBottle.glb",
    "alien-slime1-albedo.png",
    "alien-slime1-metallic.png",
    "alien-slime1-normal-dx.png",
    "alien-slime1-roughness.png",
    "buddha.obj",
    "greasy-pan-2-albedo.png",
    "greasy-pan-2-metal.png",
    "greasy-pan-2-normal.png",
    "greasy-pan-2-roughness.png",
    "grimy-metal-albedo.png",
    "grimy-metal-metalness.png",
    "grimy-metal-normal-dx.png",
    "grimy-metal-roughness.png",
    "iron-rusted4-basecolor.png",
    "iron-rusted4-metalness.png",
    "iron-rusted4-normal.png",
    "iron-rusted4-roughness.png",
    "pbr.glsl_fragment",
    "pbr.glsl_vertex",
    "sportsCar.mtl",
    "sportsCar.obj",
    "steelplate1_albedo.png",
    "steelplate1_metallic.png",
    "steelplate1_normal.png",
    "steelplate1_roughness.png",
    "teapot.mesh",
    "viking_room.obj",
    "viking_room.png",
  ]

  outputs = [ "$root_out_dir/assets/teapot/{{source_file_part}}" ]
}
