copy("teapot") {
  sources = [
    "alley-brick-wall_albedo.png",
    "alley-brick-wall_height.png",
    "alley-brick-wall_metallic.png",
    "alley-brick-wall_normal-dx.png",
    "alley-brick-wall_roughness.png",
    "alley-brick-wall_ao.png",
    "buddha.obj",
    "greasy-pan-2-albedo.png",
    "greasy-pan-2-metal.png",
    "greasy-pan-2-normal.png",
    "greasy-pan-2-roughness.png",
    "grimy-metal-albedo.png",
    "grimy-metal-metalness.png",
    "grimy-metal-normal-dx.png",
    "grimy-metal-roughness.png",
    "iron-rusted4-basecolor.png",
    "iron-rusted4-metalness.png",
    "iron-rusted4-normal.png",
    "iron-rusted4-roughness.png",
    "pbr.glsl_fragment",
    "pbr.glsl_vertex",
    "sportsCar.mtl",
    "sportsCar.obj",
    "steelplate1_albedo.png",
    "steelplate1_ao.png",
    "steelplate1_height.png",
    "steelplate1_metallic.png",
    "steelplate1_normal.png",
    "steelplate1_roughness.png",
    "teapot.mesh",
    "viking_room.obj",
    "viking_room.png",
  ]

  outputs = [ "$root_out_dir/assets/teapot/{{source_file_part}}" ]
}
