import("//build/rules.gni")

game("teapot") {
  sources = [
    "camera.cc",
    "camera.h",
    "components.h",
    "ecs.h",
    "fly_camera.cc",
    "fly_camera.h",
    "input_system.cc",
    "input_system.h",
    "scene.cc",
    "scene.h",
    "teapot.cc",
  ]
  deps = [
    "//assets/teapot",
    "//src/base",
    "//src/engine",
  ]
}
