source_set("platform") {
  sources = [
    "asset_file.cc",
    "asset_file.h",
    "platform.h",
    "platform_observer.h",
  ]

  libs = []
  deps = [ "//src/base" ]

  if (target_os == "linux" || target_os == "win") {
    sources += [
      "asset_file_generic.cc",
      "platform_glfw.cc",
    ]
    deps += [ "//src/third_party/glfw" ]
  }

  if (target_os == "android") {
    sources += [
      "asset_file_android.cc",
      "platform_android.cc",
    ]
    libs += [
      "android",
      "EGL",
      "GLESv3",
      "log",
      "z",
    ]
    deps += [
      "//src/third_party/android",
      "//src/third_party/minizip",
    ]
  }
}
