source_set("engine") {
  if (target_os != "win") {
    cflags = [ "-Wno-deprecated-declarations" ]
  }

  sources = [
    "asset/font.cc",
    "asset/font.h",
    "asset/image.cc",
    "asset/image.h",
    "asset/mesh.cc",
    "asset/mesh.h",
    "asset/shader_source.cc",
    "asset/shader_source.h",
    "asset/sound.cc",
    "asset/sound.h",
    "components.h",
    "debug_layer.cc",
    "debug_layer.h",
    "ecs.h",
    "engine.cc",
    "engine.h",
    "fly_camera.cc",
    "fly_camera.h",
    "game.h",
    "game_factory.h",
    "imgui_backend.cc",
    "imgui_backend.h",
    "input_system.cc",
    "input_system.h",
    "model.cc",
    "model.h",
    "orbit_camera.cc",
    "orbit_camera.h",
    "sound_player.cc",
    "sound_player.h",
    "system.h",
    "world.cc",
    "world.h",
  ]

  deps = [
    "//assets/engine",
    "//src/base",
    "//src/engine/audio",
    "//src/engine/platform",
    "//src/engine/renderer",
    "//src/third_party/imgui",
    "//src/third_party/jsoncpp",
    "//src/third_party/meshoptimizer",
    "//src/third_party/minimp3",
    "//src/third_party/stb",
    "//src/third_party/texture_compressor",
    "//src/third_party/tiny_obj_loader",
    "//src/third_party/tinygltf",
  ]
}
