source_set("renderer") {
  sources = [
    "renderer.cc",
    "renderer.h",
    "renderer_types.cc",
    "renderer_types.h",
    "render_graph.cc",
    "render_graph.h",
    "vulkan/renderer_vulkan.cc",
    "vulkan/vulkan_context.cc",
  ]

  if (target_os == "linux") {
    sources += [
      "vulkan/renderer_vulkan_linux.cc",
      "vulkan/vulkan_context_linux.cc",
    ]
  } else if (target_os == "win") {
    sources += [
      "vulkan/renderer_vulkan_win.cc",
      "vulkan/vulkan_context_win.cc",
    ]
  } else if (target_os == "android") {
    sources += [
      "vulkan/renderer_vulkan_android.cc",
      "vulkan/vulkan_context_android.cc",
    ]
  }

  deps = [
    "//src/base",
    "//src/third_party/glslang",
    "//src/third_party/spirv-reflect",
  ]

  public_deps = [
    "//src/third_party/vma",
    "//src/third_party/volk",
  ]

  if (target_os == "android") {
    deps += [ "//src/third_party/android" ]
  }
}
